[package]
name = "michibot"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
tokenizers = { version = "0.21.1", default-features = false, features = [
  "onig",
  "http",
  "unstable_wasm",
] }

[workspace]
members = ["burn_inference"]
resolver = "2"
