[package]
name = "michibot"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.16.1", features = ["train", "wgpu", "dataset", "tui"] }
tokenizers = { version = "0.21.1", default-features = false, features = [
  "onig",
  "http",
  "unstable_wasm",
] }
